# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20170821_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.IntegerField(null=True),
        ),
    ]
