# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20170821_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='since',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
