# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20170821_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPayments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('drg_definition', models.CharField(max_length=255)),
                ('provider_id', models.IntegerField()),
                ('provider_name', models.CharField(max_length=255)),
                ('provider_street_address', models.CharField(max_length=255)),
                ('provider_city', models.CharField(max_length=255)),
                ('provider_state', models.CharField(max_length=255)),
                ('provider_zipcode', models.CharField(max_length=255)),
                ('hospital_referral_region_description', models.CharField(max_length=255)),
                ('total_discharges', models.IntegerField()),
                ('average_covered_charges', models.DecimalField(decimal_places=2, max_digits=100)),
                ('average_total_payments', models.DecimalField(decimal_places=2, max_digits=100)),
                ('average_medicare_payments', models.DecimalField(decimal_places=2, max_digits=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
